# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loss_kmeans <- function(x_cluster) {
    .Call('_GBClust_loss_kmeans', PACKAGE = 'GBClust', x_cluster)
}

loss_average <- function(D_cluster) {
    .Call('_GBClust_loss_average', PACKAGE = 'GBClust', D_cluster)
}

loss_kmeans2 <- function(x_cluster) {
    .Call('_GBClust_loss_kmeans2', PACKAGE = 'GBClust', x_cluster)
}

kdissimilarities_C <- function(D, G, freq, trace) {
    .Call('_GBClust_kdissimilarities_C', PACKAGE = 'GBClust', D, G, freq, trace)
}

Gibbs_kmeans_C <- function(R, X, a_lambda, b_lambda, G, freq, trace) {
    .Call('_GBClust_Gibbs_kmeans_C', PACKAGE = 'GBClust', R, X, a_lambda, b_lambda, G, freq, trace)
}

Gibbs_Mink_C <- function(R, D, d, a_lambda, b_lambda, G, freq, trace) {
    .Call('_GBClust_Gibbs_Mink_C', PACKAGE = 'GBClust', R, D, d, a_lambda, b_lambda, G, freq, trace)
}

sample_centroids <- function(x, k) {
    .Call('_GBClust_sample_centroids', PACKAGE = 'GBClust', x, k)
}

kmeans_C <- function(x, m, k, trace) {
    .Call('_GBClust_kmeans_C', PACKAGE = 'GBClust', x, m, k, trace)
}

kmeans2_C <- function(x, m, k, trace) {
    .Call('_GBClust_kmeans2_C', PACKAGE = 'GBClust', x, m, k, trace)
}

